### PR TITLE
vainfo: Add FEI and Statistics entry points

### PR DESCRIPTION
**Pull request by sreerenjb**

### CODE REVIEW

**Comment by uartie** [comment]
@sreerenjb please provide a link to the libva PR that this depends on.  Thanks.

**Comment by uartie** [comment]
Also, "m_vaBufferTypes" probably needs updated in test/test_data.h

**Comment by sreerenjb** [comment]
Will do those. Thanks.

**Comment by sreerenjb** [comment]
Removed the Statistics entrypoint from the first patch since we might split the FEI patches to libva (to only add FEI support first and Statistics in future).
Updated the original patch and added FEI primitives in test cases.

**Comment by xhaihao** [comment]
@sreerenjb could you also update the dependency on VA-API for libva-utils?

**Comment by sreerenjb** [comment]
@xhaihao  Done.

**Pull request merged**
